DROP TABLE IF EXISTS `attendance_regularization`;

CREATE TABLE `attendance_regularization` (
  `id` int NOT NULL AUTO_INCREMENT,
  `employee_id` int DEFAULT NULL,
  `date` date DEFAULT NULL,
  `requested_in_time` time DEFAULT NULL,
  `requested_out_time` time DEFAULT NULL,
  `request_type` enum('Regularization','OnDuty') DEFAULT NULL,
  `regularization_shift_type` enum('FullDay','FirstHalf','SecondHalf') DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `status` enum('Pending','Approved','Rejected') DEFAULT NULL,
  `created_on` datetime DEFAULT NULL,
  `approved_by` int DEFAULT NULL,
  `approved_on` datetime DEFAULT NULL,
  `substitute_employee_id` int DEFAULT NULL,
  `approver_1_id` int DEFAULT NULL,
  `approver_2_id` int DEFAULT NULL,
  `current_level` tinyint NOT NULL DEFAULT '1',
  `approver_1_remarks` text,
  `approver_1_action_on` datetime DEFAULT NULL,
  `approver_2_remarks` text,
  `approver_2_action_on` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_ar_substitute` (`substitute_employee_id`),
  KEY `fk_ar_approver1` (`approver_1_id`),
  KEY `fk_ar_approver2` (`approver_2_id`),
  CONSTRAINT `fk_ar_approver1` FOREIGN KEY (`approver_1_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_ar_approver2` FOREIGN KEY (`approver_2_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_ar_substitute` FOREIGN KEY (`substitute_employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=226 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
