DROP TABLE IF EXISTS `leave_requests`;

CREATE TABLE `leave_requests` (
  `leave_request_id` int NOT NULL AUTO_INCREMENT,
  `employee_id` int NOT NULL,
  `leave_type` varchar(50) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `total_days` decimal(5,2) NOT NULL,
  `leave_half_type` enum('FullDay','FirstHalf','SecondHalf') DEFAULT 'FullDay',
  `reason` text,
  `status` enum('Pending','Approved','Rejected','Cancelled') DEFAULT 'Pending',
  `applied_on` datetime DEFAULT CURRENT_TIMESTAMP,
  `approved_by_id` int DEFAULT NULL,
  `approved_on` datetime DEFAULT NULL,
  `rejection_reason` text,
  `attachment_path` varchar(512) DEFAULT NULL,
  `substitute_employee_id` int DEFAULT NULL,
  `approver_1_id` int DEFAULT NULL,
  `approver_2_id` int DEFAULT NULL,
  `current_level` tinyint NOT NULL DEFAULT '1',
  `approver_1_remarks` text,
  `approver_1_action_on` datetime DEFAULT NULL,
  `approver_2_remarks` text,
  `approver_2_action_on` datetime DEFAULT NULL,
  `is_paid` tinyint NOT NULL DEFAULT '1',
  PRIMARY KEY (`leave_request_id`),
  KEY `fk_leave_request_employee` (`employee_id`),
  KEY `fk_lr_substitute` (`substitute_employee_id`),
  KEY `fk_lr_approver1` (`approver_1_id`),
  KEY `fk_lr_approver2` (`approver_2_id`),
  CONSTRAINT `fk_leave_request_employee` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_lr_approver1` FOREIGN KEY (`approver_1_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_lr_approver2` FOREIGN KEY (`approver_2_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_lr_substitute` FOREIGN KEY (`substitute_employee_id`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=93 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
