DROP TABLE IF EXISTS `salary_disbursement`;

CREATE TABLE `salary_disbursement` (
  `disbursement_id` int NOT NULL AUTO_INCREMENT,
  `employee_id` int NOT NULL,
  `structure_id` int NOT NULL,
  `period_id` int NOT NULL,
  `basic_pay` decimal(15,2) NOT NULL,
  `hra` decimal(15,2) NOT NULL DEFAULT '0.00',
  `educational_allowance` decimal(15,2) NOT NULL DEFAULT '0.00',
  `special_allowance` decimal(15,2) NOT NULL DEFAULT '0.00',
  `naac_allowance` decimal(15,2) NOT NULL DEFAULT '0.00',
  `gross_salary` decimal(15,2) NOT NULL,
  `lop_days` decimal(5,2) NOT NULL DEFAULT '0.00',
  `payable_amount` decimal(15,2) NOT NULL,
  `deductions_json` json DEFAULT NULL,
  `total_deduction` decimal(15,2) NOT NULL DEFAULT '0.00',
  `net_salary` decimal(15,2) NOT NULL,
  `status` enum('draft','submitted','verified','approved','paid','rejected') NOT NULL DEFAULT 'draft',
  `prepared_by` int DEFAULT NULL,
  `prepared_on` datetime DEFAULT NULL,
  `verified_by` int DEFAULT NULL,
  `verified_on` datetime DEFAULT NULL,
  `verified_remarks` varchar(255) DEFAULT NULL,
  `approved_by` int DEFAULT NULL,
  `approved_on` datetime DEFAULT NULL,
  `approved_remarks` varchar(255) DEFAULT NULL,
  `rejected_by` int DEFAULT NULL,
  `rejected_on` datetime DEFAULT NULL,
  `rejected_remarks` varchar(255) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`disbursement_id`),
  UNIQUE KEY `uq_disbursement_employee_period` (`employee_id`,`period_id`),
  KEY `fk_disb_struct` (`structure_id`),
  KEY `fk_disb_period` (`period_id`),
  KEY `fk_disb_prep` (`prepared_by`),
  KEY `fk_disb_veri` (`verified_by`),
  KEY `fk_disb_appr` (`approved_by`),
  CONSTRAINT `fk_disb_appr` FOREIGN KEY (`approved_by`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_disb_emp` FOREIGN KEY (`employee_id`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_disb_period` FOREIGN KEY (`period_id`) REFERENCES `payroll_period` (`period_id`),
  CONSTRAINT `fk_disb_prep` FOREIGN KEY (`prepared_by`) REFERENCES `employee` (`employee_id`),
  CONSTRAINT `fk_disb_struct` FOREIGN KEY (`structure_id`) REFERENCES `salary_structure` (`structure_id`),
  CONSTRAINT `fk_disb_veri` FOREIGN KEY (`verified_by`) REFERENCES `employee` (`employee_id`)
) ENGINE=InnoDB AUTO_INCREMENT=709 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
